data_set_names = ['Amazon2014-Amazon-Instant-Video', 'Amazon2014-Apps-For-Android', 'Amazon2014-Automotive',
                  'Amazon2014-Baby', 'Amazon2014-Beauty', 'Amazon2014-Cell-Phones-And-Accessories',
                  'Amazon2014-Clothing-Shoes-And-Jewelry', 'Amazon2014-Digital-Music',
                  'Amazon2014-Grocery-And-Gourmet', 'Amazon2014-Health-And-Personal-Care',
                  'Amazon2014-Home-And-Kitchen', 'Amazon2014-Musical-Instruments',
                  'Amazon2014-Office-Products', 'Amazon2014-Patio-Lawn-And-Garden', 'Amazon2014-Pet-Supplies',
                  'Amazon2014-Sports-And-Outdoors', 'Amazon2014-Tools-And-Home-Improvement',
                  'Amazon2014-Toys-And-Games', 'Amazon2014-Video-Games', 'Amazon2018-Digital-Music',
                  'Amazon2018-Gift-Cards', 'Amazon2018-Industrial-And-Scientific', 'Amazon2018-Luxury-Beauty',
                  'Amazon2018-Magazine-Subscriptions', 'Amazon2018-Musical-Instruments', 'Amazon2018-Prime-Pantry',
                  'Amazon2018-Software', 'Behance', 'BookCrossing', 'CiaoDVD', 'CiteULike-A', 'CiteULike-T',
                  'DeliveryHero-SE', 'Diginetica', 'Docear-Mind-Maps', 'Epinions', 'Escorts', 'FilmTrust',
                  'Foursquare-NYC1', 'Foursquare-NYC2', 'Foursquare-Tokyo', 'Frappe', 'GoogleLocal2021-Alaska',
                  'GoogleLocal2021-District-Of-Columbia', 'GoogleLocal2021-North-Dakota',
                  'GoogleLocal2021-South-Dakota', 'GoogleLocal2021-Vermont', 'GoogleLocal2021-Wyoming', 'Hetrec-LastFM',
                  'Jester-4', 'KGRec-Music', 'LearningFromSets', 'MarketBias-ModCloth', 'ModCloth-Clothing-Fit',
                  'MovieLens-100K', 'MovieLens-1M', 'MovieLens-Latest-Small', 'MovieTweetings', 'Myket-Android',
                  'Personality', 'Rekko', 'RentTheRunway', 'Retailrocket', 'Sketchfab', 'StackOverflow',
                  'Steam-Australian-Reviews', 'TaFeng', 'Twitch-Full', 'WikiLens', 'Yahoo-Movies', 'Yahoo-Music3',
                  'Yahoo-Semi-Synthetic']

available_data_set_names = ['Amazon2014-Amazon-Instant-Video', 'Amazon2014-Apps-For-Android', 'Amazon2014-Automotive',
                            'Amazon2014-Baby', 'Amazon2014-Beauty', 'Amazon2014-Cell-Phones-And-Accessories',
                            'Amazon2014-Clothing-Shoes-And-Jewelry', 'Amazon2014-Digital-Music',
                            'Amazon2014-Grocery-And-Gourmet', 'Amazon2014-Health-And-Personal-Care',
                            'Amazon2014-Home-And-Kitchen', 'Amazon2014-Musical-Instruments',
                            'Amazon2014-Office-Products', 'Amazon2014-Patio-Lawn-And-Garden', 'Amazon2014-Pet-Supplies',
                            'Amazon2014-Sports-And-Outdoors', 'Amazon2014-Tools-And-Home-Improvement',
                            'Amazon2014-Toys-And-Games', 'Amazon2014-Video-Games', 'Amazon2018-Digital-Music',
                            'Amazon2018-Gift-Cards', 'Amazon2018-Industrial-And-Scientific', 'Amazon2018-Luxury-Beauty',
                            'Amazon2018-Magazine-Subscriptions', 'Amazon2018-Musical-Instruments',
                            'Amazon2018-Prime-Pantry', 'Amazon2018-Software', 'Behance', 'BookCrossing', 'CiaoDVD',
                            'CiteULike-A', 'CiteULike-T', 'DeliveryHero-SE', 'Diginetica', 'Docear-Mind-Maps',
                            'Epinions', 'Escorts', 'FilmTrust', 'Foursquare-NYC1', 'Foursquare-NYC2',
                            'Foursquare-Tokyo', 'Frappe', 'GoogleLocal2021-Alaska',
                            'GoogleLocal2021-District-Of-Columbia', 'GoogleLocal2021-North-Dakota',
                            'GoogleLocal2021-South-Dakota', 'GoogleLocal2021-Vermont', 'GoogleLocal2021-Wyoming',
                            'Hetrec-LastFM', 'Jester-4', 'KGRec-Music', 'LearningFromSets', 'MarketBias-ModCloth',
                            'ModCloth-Clothing-Fit', 'MovieLens-100K', 'MovieLens-1M', 'MovieLens-Latest-Small',
                            'MovieTweetings', 'Myket-Android', 'Personality', 'Rekko', 'RentTheRunway', 'Retailrocket',
                            'Sketchfab', 'StackOverflow', 'Steam-Australian-Reviews', 'TaFeng', 'Twitch-Full',
                            'WikiLens', 'Yahoo-Movies', 'Yahoo-Music3', 'Yahoo-Semi-Synthetic']
